# Generated by Django 4.1.1 on 2022-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0002_entregable_estudiantes_profesor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("disponibilidad", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Turnos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicio", models.CharField(max_length=60)),
                ("nombre", models.CharField(max_length=60)),
                ("fechaTurno", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Entregable",
        ),
        migrations.DeleteModel(
            name="Estudiantes",
        ),
        migrations.DeleteModel(
            name="Profesor",
        ),
    ]
