# Generated by Django 4.1.1 on 2022-09-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0003_productos_turnos_delete_entregable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productos",
            old_name="disponibilidad",
            new_name="marca",
        ),
    ]
